### ISSUE TITLE
Endless loop of livewire-ui-modal requests on close

### ISSUE THREAD

**Issue by seabasss** [wire-elements/modal#192] opened 2022-03-02 21:12 UTC
Seemingly out of nowhere the modal started to trigger endless network requests every time I close the modal, and I have to reload the browser until I can open the modal again, and same problem happens again...

It worked without issues yesterday and after updating OS X Monterey today this problem showed up (related or not). 

I realize it's not a lot to go by and it's likely that this is on my end, but any ideas of what I can try?
It's still working in one app but not the other, even after reverting to way older commits and reinstalling dependencies, clearing cache and restarting machine etc.

Thanks for any leads!

![modal](https://user-images.githubusercontent.com/5251896/156450282-a044f94b-88e7-4842-9503-d96bbad06ba3.png)

**Comment by PhiloNL** [comment] 2022-03-02 21:18
Seems to be caused by the latest version of Alpine https://github.com/wire-elements/modal/discussions/191 
I'm still looking into the issue.

**Comment by PhiloNL** [comment] 2022-03-03 17:17
Should be fixed https://github.com/wire-elements/modal/releases/tag/1.0.5

**Closed by PhiloNL** 2022-03-03 17:17 UTC
