### ISSUE TITLE
Unable to change Modal Width

### ISSUE THREAD

**Issue by cpiggott** [wire-elements/modal#228] opened 2022-05-16 17:25 UTC
Hello! I've recently updated to TailwindCSS v3.0.0 + and cannot change the size of a modal anymore.

I'm unable to make a modal bigger than 448 pixels. No matter what I do.

I've tried setting the maxWidth in the model, I've added the array of max-w to the tailwind.config.js whitelist.

Not sure what else to try.

**Comment by PhiloNL** [comment] 2022-05-16 19:15
Hi @cpiggott,
If you can create a repository with a fresh install of Laravel, Livewire, and Tailwind and reproduce the problem, I'm able to investigate further.

**Comment by dhruva81** [comment] 2022-05-17 05:12
I am also facing same issue. 
I have several modals with different width and they were working fine previously.
But now.. all modals have same width.
Not able to fix this issue :(

**Comment by jiaoliness** [comment] 2022-05-18 05:01
Also have the same issue. Neither the config nor setting the modalMaxWidth property changes the size of the modal

**Comment by PhiloNL** [comment] 2022-05-18 12:54
If they were working fine previously it must be related to something else given no recent changes were made to this component.

**Comment by rayehizoba** [comment] 2022-05-18 14:12
I recently had this issue as well. This comment helped - https://github.com/wire-elements/modal/issues/150#issuecomment-1022171394

**Comment by dhruva81** [comment] 2022-05-21 12:29
Thank you @rayehizoba 

The issue is fixed by adding following in `tailwind.config.js`

```
safelist: [
   {
      pattern: /max-w-(sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)/,
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
   },
],

```

**Closed** 2022-06-04 20:46 UTC

**Comment by magarrent** [comment] 2023-01-20 09:09
> Thank you @rayehizoba
> 
> The issue is fixed by adding following in `tailwind.config.js`
> 
> ```
> safelist: [
>    {
>       pattern: /max-w-(sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)/,
>       variants: ['sm', 'md', 'lg', 'xl', '2xl'],
>    },
> ],
> ```

Hey it works! Can you please update it to Readme?

**Comment by jeffchown** [comment] 2023-05-29 14:46
Thanks for this!
