### ISSUE TITLE
Upgrading to the beta version - No hint path defined for ['livewire-ui-modal']

### ISSUE THREAD

**Issue by Astalyos** [wire-elements/modal#338] opened 2023-07-31 06:55 UTC
Hello there ! 
Thank you for keeping it up to date and making it compatible with the V3 of Livewire ! 
Unfortunately we had trouble when upgrading from the previous version to the beta one
We encountered this error : 
`No hint path defined for [livewire-ui-modal]`

Related to this line in our main blade file : 
`@livewire('wire-elements-modal')`

We upgraded Livewire and the modal package in the same time, and followed the upgrade guide but something apparently went wrong. Any idea what might cause this?

**Comment by PhiloNL** [comment] 2023-07-31 10:16
Hi there! Which beta version are you using? I think this should be fixed in the latest release.

**Comment by DanielSpravtsev** [comment] 2023-07-31 11:07
@PhiloNL  Same problem. Last beta (2.0.3-beta). Trying to figure out how to fix that :)

**Comment by DanielSpravtsev** [comment] 2023-07-31 11:24
It is caused by old namespace (livewire-ui-modal) in modal/src/Modal.php. It fixed in master, but with old namespaces in 2.0.3-beta @PhiloNL @Astalyos

**Comment by PhiloNL** [comment] 2023-07-31 12:21
Tagged a new release, let me know if that solved the issue :)

**Comment by DanielSpravtsev** [comment] 2023-07-31 14:22
2.0.4-beta fixes problem, thanks @PhiloNL !

**Closed** 2023-07-31 22:25 UTC
